---

- name: Install i3 theme libs
  become: true
  yum:
    name: "{{item}}"
    state: present
  with_items:
    - xorg-x11-server-Xorg
    - xorg-x11-xinit
    - i3
    - dmenu
    - conky
    - i3lock
    - fontawesome-fonts
    - xprop
    - perl-AnyEvent-I3
    - xterm

- name: Install xorg drivers
  become: true
  shell: |
    yum -y install "xorg-x11-drv*"

- name: Install required fonts
  become: yes
  get_url: 
    url: "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/SourceCodePro/Regular/complete/Sauce%20Code%20Pro%20Nerd%20Font%20Complete%20Mono.ttf"
    dest: "/usr/share/fonts/Sauce Code Pro Nerd Font Complete Mono.ttf"

- name: Refresh font cache
  become: yes
  shell: |
    fc-cache -r

- name: Install build deps
  become: true
  yum:
    name: "{{item}}"
    state: present
  with_items:
    - gcc-c++
    - perl
    - redhat-rpm-config
    - perl-ExtUtils-ParseXS
    - libX11
    - libX11-devel
    - libXft
    - libXft-devel
    - perl-ExtUtils-Embed

- name: Enable GUI
  become: true
  shell: |
    systemctl set-default graphical.target
