---

- name: Copy .files
  copy:
    src: "../{{item}}"
    dest: "~/"
  with_items:
    - ".config"
    - ".i3"
    - ".vimrc"
    - ".zsh.d"
    - ".zshrc"
    - ".Xresources"
    - ".xinitrc"

- name: Fix Permissions
  file:
    path: ~/.i3/conky-i3bar
    mode: 0774

- name : Load Xresources
  shell: |
    xrdb ~/.Xresources
