---
# tasks file for alexdevbox


- name: Update erstmal
  become: true
  shell: |
    yum -y update

- include_tasks: packages.yml
- include_tasks: desktop.yml
- include_tasks: chrome.yml
- include_tasks: dunst.yml
- include_tasks: dotfiles.yml
- include_tasks: zsh.yml

- name: Reboot
  become: yes
  shell: |
    reboot

