---

- name: Install the best of the best
  become: true
  yum:
    name: "{{item}}"
    state: present
  with_items:
    - net-tools
    - bind-utils
    - jq
    - vim
    - git
    - htop
    - iotop
    - tmux
    - wget
    - curl
    - autoconf
    - automake
    - gcc
    - zsh
    - createrepo 
    - python34
    - pulseaudio
    - GConf2
    - alsa-utils
    - gnome-keyring
    - gnome-keyring-pam
    - libgnome-keyring
    - ruby
    - bzip2
    - unzip

- name: Create local Repo
  become: true
  file:
    path: /srv/yum-repo
    state: directory

- name: Create rpm Repodata
  become: true
  shell: |
    createrepo /srv/yum-repo

- name: Copy repo file  
  become: yes
  copy:
    src: ../local.repo
    dest: /etc/yum.repos.d/local.repo
  
