---

- name: Clone copyq
  shell: |
    cd /tmp && git clone https://github.com/hluk/CopyQ.git

- name: Make copyq
  shell: |
    cd /tmp/CopyQ && cmake -DCMAKE_INSTALL_PREFIX=/usr/local . && make

- name: Install copyq
  become: yes
  shell: |
    cd /tmp/CopyQ && make install